/**
 * @file scripts/lib/__tests__/gh-throttle.shim-routed.test.mjs
 * @description gh-budget-burn — live 2026-10-10 20:25Z and 21:28Z. The operator's PERSONAL stored login (5,000/h
 *   core) ran out while the App installation (15,000/h) still had ~11,500 left. A daemon whose `gh` is the per-owner
 *   App shim carries no GH_TOKEN itself, so runGhSync labelled every call `default` — the same label as a genuine
 *   personal-login call. The personal exhaustion wrote `budget-block-default-core.json`, and that block then refused
 *   267 App-routed calls in 5 minutes (await-verify-loop 60, reconcile-fix 52, merge-ai-prs 43, review-daemon 32 …):
 *   the drain's "facts-incomplete" and ci-red-recovery-watch's "shared backoff" exits.
 *   Proves: when `gh` on PATH is the WE App shim, the OUTER runGhSync neither reads nor writes the `default` block —
 *   the nested passthrough inside the shim gates on the credential it really uses; a plain `gh` keeps the old gate.
 */
import { describe, it, expect, afterAll } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, chmodSync, existsSync, readFileSync, statSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runGhSync, writeBudgetBlock, readBudgetBlock, ghBinIsWeShim, ghThrottleLogPath, rotateGhCallLogIfLarge, resolveGhCallLogMaxBytes, DEFAULT_GH_CALL_LOG_MAX_BYTES } from '../gh-throttle.mjs';

const NOW = Date.parse('2026-10-10T21:30:00Z');
const made = [];
const tmp = (p) => { const d = mkdtempSync(join(tmpdir(), p)); made.push(d); return d; };
afterAll(() => { for (const d of made) rmSync(d, { recursive: true, force: true }); });

function binDir(kind) {
  const dir = tmp(`gh-bin-${kind}-`);
  const body = kind === 'shim'
    ? "#!/usr/bin/env node\n// AUTO-GENERATED by we:scripts/lib/gh-app-shim.mjs — regenerated on every dispatch; do not edit by hand.\n"
    : '#!/bin/sh\necho real gh\n';
  writeFileSync(join(dir, 'gh'), body);
  chmodSync(join(dir, 'gh'), 0o755);
  return dir;
}

function opts(lockRoot, pathDir, exec) {
  return {
    encoding: 'utf8',
    env: { PATH: pathDir, HOME: '/h' }, // no GH_TOKEN: the shim (if any) picks the credential per call
    throttle: { lockRoot, cap: 4, sleep: () => {}, now: () => NOW, env: {}, maxAttempts: 3, retryBaseMs: 1, exec },
  };
}

describe('ghBinIsWeShim', () => {
  it('true only when the first `gh` on PATH is the generated WE App shim', () => {
    const shim = binDir('shim'); const real = binDir('real');
    expect(ghBinIsWeShim('gh', { PATH: `${shim}:${real}` })).toBe(true);
    expect(ghBinIsWeShim('gh', { PATH: `${real}:${shim}` })).toBe(false);
    expect(ghBinIsWeShim('gh', { PATH: '' })).toBe(false);
    expect(ghBinIsWeShim(join(shim, 'gh'), {})).toBe(true);
    expect(ghBinIsWeShim(join(real, 'gh'), {})).toBe(false);
  });
});

describe('runGhSync — a personal-login block never stalls App-shim-routed calls', () => {
  it('a shim-routed call still runs while budget-block-default-core is active, and is tagged via=shim', () => {
    const lockRoot = tmp('gh-shimroute-');
    writeBudgetBlock(lockRoot, 'default', 'core', { untilMs: NOW + 5 * 60_000, nowMs: NOW, source: 'header' });
    let calls = 0;
    const out = runGhSync(['api', 'repos/web-everything/web-everything/pulls/1'], opts(lockRoot, binDir('shim'), () => { calls += 1; return '{"ok":1}'; }));
    expect(out).toBe('{"ok":1}');
    expect(calls).toBe(1);
    const lines = readFileSync(ghThrottleLogPath(lockRoot), 'utf8').trim().split('\n').map((l) => JSON.parse(l));
    expect(lines.some((l) => l.outcome === 'budget_blocked')).toBe(false);
    expect(lines.find((l) => l.outcome === 'call')).toMatchObject({ id: 'default', via: 'shim' });
  });

  it('a primary exhaustion relayed through the shim does NOT write a `default` block (the inner layer owns it) and is not retried', () => {
    const lockRoot = tmp('gh-shimroute-');
    let calls = 0;
    const exec = () => {
      calls += 1;
      const e = new Error('gh-throttle: GitHub core API rate limit exceeded for this identity — shared backoff until 2026-10-10T21:45:56.000Z, call not sent (#gh-graphql-budget)');
      e.status = 1; e.stderr = `${e.message}\n`; e.stdout = '';
      throw e;
    };
    expect(() => runGhSync(['api', 'repos/web-everything/web-everything/pulls/1'], opts(lockRoot, binDir('shim'), exec))).toThrow(/shared backoff/);
    expect(calls).toBe(1);
    expect(readBudgetBlock(lockRoot, 'default', 'core', NOW)).toBe(null);
    expect(existsSync(join(lockRoot, 'budget-block-default-core.json'))).toBe(false);
  });

  it('regression guard: a plain `gh` (real stored login) is still refused by the default block', () => {
    const lockRoot = tmp('gh-shimroute-');
    writeBudgetBlock(lockRoot, 'default', 'core', { untilMs: NOW + 5 * 60_000, nowMs: NOW, source: 'header' });
    let calls = 0;
    expect(() => runGhSync(['api', 'repos/web-everything/web-everything/pulls/1'], opts(lockRoot, binDir('real'), () => { calls += 1; return '{}'; }))).toThrow(/shared backoff/);
    expect(calls).toBe(0);
  });

  it('call log rotates past the configured size, keeping one generation and logging the rotation', () => {
    const dir = tmp('gh-calllog-');
    const logPath = join(dir, 'calls.jsonl');
    writeFileSync(logPath, 'x'.repeat(2 * 1024 * 1024));
    expect(resolveGhCallLogMaxBytes({ WE_GH_CALL_LOG_MAX_BYTES: String(1024 * 1024) })).toBe(1024 * 1024);
    expect(resolveGhCallLogMaxBytes({ WE_GH_CALL_LOG_MAX_BYTES: '10' })).toBe(DEFAULT_GH_CALL_LOG_MAX_BYTES);
    expect(rotateGhCallLogIfLarge(logPath, { maxBytes: 1024 * 1024 })).toBe(true);
    expect(statSync(`${logPath}.1`).size).toBe(2 * 1024 * 1024);
    expect(JSON.parse(readFileSync(logPath, 'utf8').trim())).toMatchObject({ outcome: 'log_rotated', rotatedBytes: 2 * 1024 * 1024, maxBytes: 1024 * 1024 });
    expect(rotateGhCallLogIfLarge(logPath, { maxBytes: 1024 * 1024 })).toBe(false);
    expect(rotateGhCallLogIfLarge(join(dir, 'missing.jsonl'))).toBe(false);
  });

  it('regression guard: a plain `gh` primary exhaustion still records the shared default block', () => {
    const lockRoot = tmp('gh-shimroute-');
    mkdirSync(lockRoot, { recursive: true });
    const exec = (args) => {
      if (args[1] === 'rate_limit') return JSON.stringify({ remaining: 0, reset: Math.floor(NOW / 1000) + 600 });
      const e = new Error('gh: API rate limit exceeded for user ID 1. (HTTP 403)');
      e.status = 1; e.stderr = `${e.message}\n`; e.stdout = '';
      throw e;
    };
    expect(() => runGhSync(['api', 'repos/web-everything/web-everything/pulls/1'], opts(lockRoot, binDir('real'), exec))).toThrow(/rate limit/);
    expect(readBudgetBlock(lockRoot, 'default', 'core', NOW)).not.toBe(null);
  });
});
