/**
 * @file scripts/__tests__/lane-pool-shared-commit-graph.test.mjs
 * @description xsxu243 — a corrupt commit-graph in the SHARED reference store (the primary checkout every lane
 *   clones `--reference`) is regenerated by the pool, logged, and the failed git op retried. Reproduces the live
 *   2026-10-08 incident: the graph names a commit the object store no longer has, so `commit-graph verify` fails
 *   and every lane's history walk dies with "in the commit graph file but not in the object database".
 *   Boundary pinned: only the derived commit-graph cache may change — refs, objects and tracked files must not.
 */
import { describe, it, expect, beforeEach, afterEach, beforeAll, afterAll } from 'vitest';
import { sharedRepos } from './fixtures/shared-git-fixture.mjs';
import { spawnSync, execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync, existsSync, readdirSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import { healSharedCommitGraph, verifyCommitGraph, looksLikeCommitGraphError } from '../lib/lane-repair.mjs';

const SCRIPT = resolve(process.cwd(), 'scripts/lane-pool.mjs');
const git = (args, cwd) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();

let base, originDir, referenceDir, poolRoot, fixtureRoot, sharedFixture;

/**
 * git does not always trip over a stale shared graph on a local-path fetch (it re-fetches the "missing" object), but
 * it does for the real remote's wants (live: "You are attempting to fetch <sha>, which is in the commit graph file but
 * not in the object database"). This shim reproduces exactly that symptom, and ONLY while the reference store's
 * commit-graph really fails `git commit-graph verify`; once the pool regenerates it, fetch passes through to real git.
 */
function gitShimDir() {
  const dir = join(base, 'shim');
  mkdirSync(dir, { recursive: true });
  const real = execFileSync('which', ['git'], { encoding: 'utf8' }).trim();
  const sh = `#!/bin/bash
if [ "$1" = fetch ] && ! ${JSON.stringify(real)} -C ${JSON.stringify(referenceDir)} commit-graph verify >/dev/null 2>&1; then
  echo "fatal: You are attempting to fetch 28b0385ec6ee18314feaad2c31c979a6eea0f95f, which is in the commit graph file but not in the object database." >&2
  echo "This is probably due to repo corruption." >&2
  exit 128
fi
exec ${JSON.stringify(real)} "$@"
`;
  writeFileSync(join(dir, 'git'), sh, { mode: 0o755 });
  return dir;
}
function runPool(args, { shim = false } = {}) {
  const env = { ...process.env, LANE_POOL_ROOT: poolRoot };
  if (shim) env.PATH = `${gitShimDir()}:${process.env.PATH}`;
  const r = spawnSync('node', [SCRIPT, ...args], { encoding: 'utf8', env });
  return { code: r.status ?? 1, out: String(r.stdout || ''), err: String(r.stderr || '') };
}
const poolArgs = () => [`--origin=${originDir}`, `--reference=${referenceDir}`, '--name=sgraph', '--branch=trunk', '--no-install'];
const laneDir = () => join(poolRoot, 'sgraph', 'lane-1');
const infoDir = () => join(referenceDir, '.git', 'objects', 'info');
const lockDir = () => join(base, 'shared-commit-graph.lock');

/** Make the reference's commit-graph name a commit that is then pruned from the object store (what gc left behind). */
function corruptSharedGraph() {
  const tree = git(['rev-parse', 'HEAD^{tree}'], referenceDir);
  const ghost = git(['commit-tree', tree, '-m', 'ghost'], referenceDir);
  execFileSync('git', ['commit-graph', 'write', '--stdin-commits', '--no-progress'], { cwd: referenceDir, input: `${ghost}\n${git(['rev-parse', 'HEAD'], referenceDir)}\n` });
  rmSync(join(referenceDir, '.git', 'objects', ghost.slice(0, 2), ghost.slice(2)), { force: true });
  return ghost;
}
const snapshotRefsAndHead = () => git(['for-each-ref', '--format=%(objectname) %(refname)'], referenceDir) + '\n' + git(['rev-parse', 'HEAD'], referenceDir) + '\n' + git(['status', '--porcelain'], referenceDir);

beforeAll(() => {
  fixtureRoot = mkdtempSync(join(tmpdir(), 'lane-pool-sgraph-fixture-'));
  originDir = join(fixtureRoot, 'origin.git');
  referenceDir = join(fixtureRoot, 'reference');
  git(['init', '--quiet', '--bare', '--initial-branch=trunk', originDir]);
  git(['clone', '--quiet', originDir, referenceDir]);
  git(['config', 'user.email', 't@t.com'], referenceDir);
  git(['config', 'user.name', 't'], referenceDir);
  writeFileSync(join(referenceDir, 'file.txt'), 'v1\n');
  git(['add', 'file.txt'], referenceDir);
  git(['commit', '--quiet', '-m', 'v1'], referenceDir);
  git(['push', '--quiet', 'origin', 'HEAD:refs/heads/trunk'], referenceDir);
  sharedFixture = sharedRepos(fixtureRoot, [originDir, referenceDir]);
});
afterAll(() => sharedFixture?.dispose());
beforeEach(() => {
  base = mkdtempSync(join(tmpdir(), 'lane-pool-sgraph-'));
  poolRoot = join(base, 'pool');
  expect(runPool(['provision', '--count=1', ...poolArgs()]).code).toBe(0);
});
afterEach(() => {
  rmSync(base, { recursive: true, force: true });
  for (const n of existsSync(infoDir()) ? readdirSync(infoDir()) : []) if (n.startsWith('commit-graph')) rmSync(join(infoDir(), n), { recursive: true, force: true });
  sharedFixture.restore();
});

describe('xsxu243 — healSharedCommitGraph', () => {
  it('detects the simulated corruption, then regenerates a clean graph and keeps the bad one aside', () => {
    corruptSharedGraph();
    expect(verifyCommitGraph(referenceDir).ok).toBe(false);
    const logs = [];
    const r = healSharedCommitGraph(referenceDir, { lockDir: lockDir(), log: (m) => logs.push(m) });
    expect(r.healed).toBe(true);
    expect(verifyCommitGraph(referenceDir).ok).toBe(true);
    expect(readdirSync(infoDir()).some((n) => n.startsWith('commit-graph.corrupt-'))).toBe(true);
    expect(logs.join('\n')).toMatch(/commit-graph was corrupt.*regenerated/);
    expect(existsSync(lockDir())).toBe(false); // lock released
  });

  it('touches ONLY the derived cache: refs, HEAD, tracked files and the working tree are unchanged', () => {
    corruptSharedGraph();
    const before = snapshotRefsAndHead();
    healSharedCommitGraph(referenceDir, { lockDir: lockDir() });
    expect(snapshotRefsAndHead()).toBe(before);
    expect(readFileSync(join(referenceDir, 'file.txt'), 'utf8')).toBe('v1\n');
    expect(git(['-c', 'core.commitGraph=false', 'fsck', '--connectivity-only', '--no-dangling'], referenceDir)).toBe('');
  });

  it('does nothing when the graph is already healthy (idempotent)', () => {
    git(['commit-graph', 'write', '--reachable', '--no-progress'], referenceDir);
    const r = healSharedCommitGraph(referenceDir, { lockDir: lockDir() });
    expect(r.healed).toBe(false);
    expect(readdirSync(infoDir()).some((n) => n.includes('.corrupt-'))).toBe(false);
  });

  it('does not heal while another live process holds the lock, and reclaims a dead holder\'s lock', () => {
    corruptSharedGraph();
    mkdirSync(lockDir());
    writeFileSync(join(lockDir(), 'owner'), JSON.stringify({ pid: process.pid, at: Date.now() })); // alive: us
    expect(healSharedCommitGraph(referenceDir, { lockDir: lockDir(), waitMs: 300 }).healed).toBe(false);
    expect(verifyCommitGraph(referenceDir).ok).toBe(false);
    writeFileSync(join(lockDir(), 'owner'), JSON.stringify({ pid: 2 ** 22 + 12345, at: Date.now() })); // dead pid
    expect(healSharedCommitGraph(referenceDir, { lockDir: lockDir(), waitMs: 300 }).healed).toBe(true);
  });

  it('classifies commit-graph messages', () => {
    expect(looksLikeCommitGraphError('fatal: ... is in the commit graph file but not in the object database')).toBe(true);
    expect(looksLikeCommitGraphError('failed to parse commit abc from object database for commit-graph')).toBe(true);
    expect(looksLikeCommitGraphError('fatal: unable to access: Could not resolve host')).toBe(false);
  });
});

describe('xsxu243 — the pool heals the shared store during acquire', () => {
  it('acquire against a corrupt shared commit-graph succeeds, logs the regeneration, and leaves the store verifying clean', () => {
    corruptSharedGraph();
    expect(verifyCommitGraph(referenceDir).ok).toBe(false);
    const r = runPool(['acquire', '--lane=1', '--session=s-sgraph', '--purpose=t', ...poolArgs()], { shim: true });
    expect(r.code, r.err).toBe(0);
    expect(r.err).toMatch(/commit-graph was corrupt.*regenerated/);
    expect(verifyCommitGraph(referenceDir).ok).toBe(true);
  });
});
