/**
 * @file worker-brief.mjs
 * @description Render the standard worker-brief block so dispatchers do not retype
 * drifting rules. Encodes operator handoff rules 20, 21, 23, 26 and "no pkill".
 * The pure renderer is shared by the injectable CLI and in-process callers.
 */
import { writeFile as defaultWriteFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { pathToFileURL } from 'node:url';

const DEFAULT_PROOF = 'Prove the change on the live case with before/after evidence (command + output), not only unit tests.';
const USAGE = `Usage: node scripts/worker-brief.mjs --purpose=<slug> --files=a,b [options]

  --purpose=<slug>        Required lowercase slug for lane and scope registration
  --files=a,b             Required allowed files; bare paths receive we:
  --edge-clone=<path>     Include daemon overlay and adoption instructions
  --proof=<text>          Override the live before/after proof requirement
  --repo=we|plateau-app   Lane repository (default: we)
  --owner=<token>         Scope-registry owner token (default: fresh per brief, so two workers with one slug stay apart)
  --report-lines=N        Positive report line limit (default: 8)
  --out=<path>            Write the brief to a file instead of stdout
  --help                 Print this usage
`;

/**
 * Render one standard block without IO or mutation of the caller's parameters.
 * @param {object} params
 * @param {string} params.purpose
 * @param {string[]|string} params.files Allowed paths, or a comma-separated list.
 * @param {string} [params.edgeClone]
 * @param {string} [params.proof]
 * @param {'we'|'plateau-app'} [params.repo]
 * @param {number} [params.reportLines]
 * @param {string} [params.owner] Registry owner token; the default is minted per call (per dispatch), which is what
 *   keeps a re-dispatch or a generic slug from colliding with another live worker's registration.
 * @returns {string} Markdown with a trailing newline.
 */
export function renderWorkerBrief({ purpose, files, edgeClone, proof = DEFAULT_PROOF, repo = 'we', reportLines = 8, owner = randomUUID().slice(0, 8) } = {}) {
  if (typeof owner !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9-]*$/.test(owner)) throw new Error('--owner must be an alphanumeric token.');
  if (typeof purpose !== 'string' || !/^[a-z0-9][a-z0-9-]*$/.test(purpose)) {
    throw new Error('--purpose must be a lowercase slug ([a-z0-9][a-z0-9-]*).');
  }
  const paths = typeof files === 'string' ? files.split(',') : files;
  if (!Array.isArray(paths) || !paths.length || paths.some(path => typeof path !== 'string' || !path.trim())) {
    throw new Error('--files requires a nonempty list of paths.');
  }
  if (!['we', 'plateau-app'].includes(repo)) throw new Error('--repo must be we or plateau-app.');
  if (!Number.isSafeInteger(reportLines) || reportLines < 1) throw new Error('--report-lines must be a positive integer.');
  const qualified = paths.map(path => path.trim()).map(path => path.includes(':') ? path : `${repo}:${path}`);
  const commaList = qualified.join(',');
  const laneRepo = repo === 'plateau-app' ? ' --repo=<plateau-app checkout>' : '';
  const edge = edgeClone ? `8. **Edge.** Overlay the fix onto the daemon clone and load it:
   \`node scripts/daemon-overlay.mjs add --clone=${edgeClone} --ref=lane/${purpose} --pr=<N> --by=chalbert\`, then
   \`WE_DAEMON_REBUILD_LOCK_WAIT_MS=900000 node scripts/lib/daemon-load-overlay.mjs --clone=${edgeClone} --ref=lane/${purpose} --pr=<N>\` (gated; run once, foreground).
   Confirm adoption with \`git -C ${edgeClone} merge-base --is-ancestor <sha> HEAD\`. Being on the overlay list is not enough.
` : '';

  return `## Standard worker rules (generated by scripts/worker-brief.mjs — do not hand-edit)

**Scope.** You may edit only these files:

${qualified.map(path => `- ${path}`).join('\n')}

Anything else is out of scope: stop and report.

1. **Free-scope pre-check.** Before editing, run
   \`node scripts/operations/free-scope-cli.mjs check --files=${commaList}\`.
   If any file is OCCUPIED (an open PR or a running agent holds it), stop and report who holds it. Do not start.
   If the verdict is UNKNOWN (exit 2: a PR list was cut off or unreadable), the scope is NOT proven free: stop and report it. Do not start.
2. **Register your scope.** \`node scripts/operations/free-scope-cli.mjs register --agent=${purpose} --owner=${owner} --purpose="${purpose}" --files=${commaList}\`.
   The \`--owner\` token is yours alone: if register refuses because the name is held by a different owner, another live worker
   shares your slug. Stop and report; never release or overwrite their entry.
   Release it when you finish, succeed or fail: \`node scripts/operations/free-scope-cli.mjs release --agent=${purpose} --owner=${owner}\`.
3. **Lane.** \`node scripts/lane-pool.mjs acquire --purpose=${purpose} --adopt${laneRepo}\` (for plateau-app add \`--repo=<plateau-app checkout>\`).
   Work only in the lane path it prints. Never branch or edit the primary checkout. Release the lane at the end:
   \`node scripts/lane-pool.mjs release --lane=<N> --session=<holder slug it printed>\`.
4. **Codex for scoped coding.** Well-scoped coding sub-tasks (tests, mechanical edits, a single-file fix with clear
   acceptance) go to Codex: \`node scripts/codex-direct-task.mjs --task-file=<f> --dir=<lane> --gate=standards\`.
   It is SYNCHRONOUS: run it in the foreground, never backgrounded, never wrapped in a wait. Review the diff before
   you commit. You keep root cause, design, edge adoption and live proof.
5. **Red-green tests through the heavy queue.** Write the failing test first, then the fix.
   Run tests with \`npm run test:unit -- <test files>\`. Running vitest directly is denied.
6. **One PR.** Commit with a tight pathspec (your files only), verify with
   \`node scripts/operations/run.mjs verify --checkout=<lane>\`, then open exactly one PR:
   \`node scripts/operations/run.mjs open-pr --ref=lane/${purpose} --title="<title>" --bodyFile=<path> --json\`.
7. **Pre-push recheck.** Right before open-pr, re-run the free-scope check excluding yourself:
   \`node scripts/operations/free-scope-cli.mjs check --files=${commaList} --exclude-agent=${purpose} --exclude-owner=${owner}\`.
   If something new holds your files (OCCUPIED), or the verdict is UNKNOWN (exit 2), stop and report instead of pushing.
${edge}
**Proof.** ${proof}

**Waiting (rule 23).** Poll only for the result of your OWN action (a command you just started), capped at 10
minutes, and only after checking the condition is reachable. Never loop on anything outside your control (another
daemon's tick, a rebuild, CI, a merge, review, load dropping): report it as PENDING with the exact command that
checks it, and end. If you need the condition to happen, cause it through the sanctioned mechanism instead of waiting.

**Processes.** Never \`pkill\`, \`killall\`, or any pattern kill. Stop only a process you started, by PID, and say
what evidence shows it is yours. Never stop the operator's dev server.

**Git.** No \`--force\`, no \`--no-verify\`, no history rewrite, no \`git add -A\`.

**Times** are America/New_York (ET).

**Report** in at most ${reportLines} lines: what changed (files), the PR number, the proof, and anything PENDING
with its check command.
`;
}

/** Run the CLI with injectable writable streams and an async or sync file writer. */
export async function main(argv, { stdout = process.stdout, stderr = process.stderr, writeFile = defaultWriteFile,
  newOwner = () => randomUUID().slice(0, 8) } = {}) {
  const flags = new Set(['purpose', 'files', 'edge-clone', 'proof', 'repo', 'report-lines', 'out', 'owner']);
  const options = {};
  let brief;
  try {
    for (const arg of argv) {
      if (arg === '--help') { options.help = true; continue; }
      const match = /^--([^=]+)=(.*)$/s.exec(arg);
      if (!match || !flags.has(match[1])) throw new Error(`Unknown or malformed flag: ${arg}`);
      if (!match[2]) throw new Error(`--${match[1]} requires a value.`);
      options[match[1]] = match[2];
    }
    if (options.help) { stdout.write(USAGE); return 0; }
    brief = renderWorkerBrief({
      purpose: options.purpose, files: options.files, edgeClone: options['edge-clone'],
      proof: options.proof, repo: options.repo, owner: options.owner ?? newOwner(),
      reportLines: options['report-lines'] === undefined ? 8 : Number(options['report-lines']),
    });
  } catch (error) {
    stderr.write(`${error.message}\n\n${USAGE}`);
    return 2;
  }
  try {
    if (options.out) await writeFile(options.out, brief, 'utf8');
    else stdout.write(brief);
    return 0;
  } catch (error) {
    stderr.write(`worker-brief: ${error.message}\n`);
    return 1;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = await main(process.argv.slice(2));
}
